[@ringpublishing/accelerator-images](../README.md) / InvalidParameter

# Class: InvalidParameter

Thrown when invalid parameters are provided.

**`Rationale`**

This error indicated that the user provided invalid data. Either the data does not match the expected format or the data is not valid for the operation.

## Hierarchy

- [`AcceleratorImageError`](AcceleratorImageError.md)

  ↳ **`InvalidParameter`**

## Table of contents

### Constructors

- [constructor](InvalidParameter.md#constructor)

### Properties

- [cause](InvalidParameter.md#cause)
- [message](InvalidParameter.md#message)
- [name](InvalidParameter.md#name)
- [stack](InvalidParameter.md#stack)
- [stackTraceLimit](InvalidParameter.md#stacktracelimit)

### Methods

- [captureStackTrace](InvalidParameter.md#capturestacktrace)
- [prepareStackTrace](InvalidParameter.md#preparestacktrace)

## Constructors

### constructor

• **new InvalidParameter**(`message`): [`InvalidParameter`](InvalidParameter.md)

#### Parameters

| Name | Type |
| :------ | :------ |
| `message` | `string` |

#### Returns

[`InvalidParameter`](InvalidParameter.md)

#### Overrides

[AcceleratorImageError](AcceleratorImageError.md).[constructor](AcceleratorImageError.md#constructor)

#### Defined in

[src/errors/index.ts:30](src/errors/index.ts:30)

## Properties

### cause

• `Optional` **cause**: `unknown`

#### Inherited from

[AcceleratorImageError](AcceleratorImageError.md).[cause](AcceleratorImageError.md#cause)

#### Defined in

node_modules/typescript/lib/lib.es2022.error.d.ts:24

___

### message

• **message**: `string`

#### Inherited from

[AcceleratorImageError](AcceleratorImageError.md).[message](AcceleratorImageError.md#message)

#### Defined in

node_modules/typescript/lib/lib.es5.d.ts:1068

___

### name

• **name**: `string`

#### Inherited from

[AcceleratorImageError](AcceleratorImageError.md).[name](AcceleratorImageError.md#name)

#### Defined in

node_modules/typescript/lib/lib.es5.d.ts:1067

___

### stack

• `Optional` **stack**: `string`

#### Inherited from

[AcceleratorImageError](AcceleratorImageError.md).[stack](AcceleratorImageError.md#stack)

#### Defined in

node_modules/typescript/lib/lib.es5.d.ts:1069

___

### stackTraceLimit

▪ `Static` **stackTraceLimit**: `number`

The `Error.stackTraceLimit` property specifies the number of stack frames
collected by a stack trace (whether generated by `new Error().stack` or
`Error.captureStackTrace(obj)`).

The default value is `10` but may be set to any valid JavaScript number. Changes
will affect any stack trace captured _after_ the value has been changed.

If set to a non-number value, or set to a negative number, stack traces will
not capture any frames.

#### Inherited from

[AcceleratorImageError](AcceleratorImageError.md).[stackTraceLimit](AcceleratorImageError.md#stacktracelimit)

#### Defined in

node_modules/@types/node/globals.d.ts:68

## Methods

### captureStackTrace

▸ **captureStackTrace**(`targetObject`, `constructorOpt?`): `void`

Creates a `.stack` property on `targetObject`, which when accessed returns
a string representing the location in the code at which
`Error.captureStackTrace()` was called.

```js
const myObject = {};
Error.captureStackTrace(myObject);
myObject.stack;  // Similar to `new Error().stack`
```

The first line of the trace will be prefixed with
`${myObject.name}: ${myObject.message}`.

The optional `constructorOpt` argument accepts a function. If given, all frames
above `constructorOpt`, including `constructorOpt`, will be omitted from the
generated stack trace.

The `constructorOpt` argument is useful for hiding implementation
details of error generation from the user. For instance:

```js
function a() {
  b();
}

function b() {
  c();
}

function c() {
  // Create an error without stack trace to avoid calculating the stack trace twice.
  const { stackTraceLimit } = Error;
  Error.stackTraceLimit = 0;
  const error = new Error();
  Error.stackTraceLimit = stackTraceLimit;

  // Capture the stack trace above function b
  Error.captureStackTrace(error, b); // Neither function c, nor b is included in the stack trace
  throw error;
}

a();
```

#### Parameters

| Name | Type |
| :------ | :------ |
| `targetObject` | `object` |
| `constructorOpt?` | `Function` |

#### Returns

`void`

#### Inherited from

[AcceleratorImageError](AcceleratorImageError.md).[captureStackTrace](AcceleratorImageError.md#capturestacktrace)

#### Defined in

node_modules/@types/node/globals.d.ts:52

___

### prepareStackTrace

▸ **prepareStackTrace**(`err`, `stackTraces`): `any`

#### Parameters

| Name | Type |
| :------ | :------ |
| `err` | `Error` |
| `stackTraces` | `CallSite`[] |

#### Returns

`any`

**`See`**

https://v8.dev/docs/stack-trace-api#customizing-stack-traces

#### Inherited from

[AcceleratorImageError](AcceleratorImageError.md).[prepareStackTrace](AcceleratorImageError.md#preparestacktrace)

#### Defined in

node_modules/@types/node/globals.d.ts:56
